import numpy as np, math
np.set_printoptions(suppress=True, precision=4)
step=lambda z:(np.asarray(z)>0).astype(float); relu=lambda z:np.maximum(0,z)
sig=lambda z:1/(1+np.exp(-np.asarray(z,float)))
print("== 9.2 Novikoff bound OR")
X=np.array([[0,0,1],[0,1,1],[1,0,1],[1,1,1]],float); y=np.array([-1,1,1,1])
w=np.array([1,1,-0.5]); w=w/np.linalg.norm(w); g=min(y*(X@w)); R=max(np.linalg.norm(X,axis=1)); print("gamma",g,"R",R,"bound",(R/g)**2)
w=np.array([2,2,-1]); w=w/np.linalg.norm(w); g=min(y*(X@w)); print("w=(2,2,-1) gamma",g,"bound",(R/g)**2)
print("== 9.3 XOR")
W=np.array([[1,1],[1,1]]); b=np.array([-0.5,-1.5]); v=np.array([1,-1]); c=-0.5
Xs=np.array([[0,0],[1,0],[0,1],[1,1]])
Z=Xs@W.T+b; H=step(Z); print(Z); print(H); print(step(H@v+c))
h1=relu(Xs.sum(1)); h2=relu(Xs.sum(1)-1); print("relu xor",h1-2*h2, h1, h2)
W1=np.array([[1,2],[0,1]]); b1=np.array([1,0]); W2=np.array([[2,-1]]); b2=np.array([3])
print("collapse W",W2@W1,"b",W2@b1+b2, "check", W2@(W1@np.array([1,1])+b1)+b2)
print("DLV: E",3*np.array([2,4])+np.array([3,1]),"F",4*np.array([2,4])+2*np.array([3,1]),"G",2*(3*np.array([2,4])+np.array([3,1]))+3*(4*np.array([2,4])+2*np.array([3,1])))
print("== 9.4")
for z in [0,0.5,1,2,4,-2]:
    s=float(sig(z)); print(z,"sig",round(s,4),"dsig",round(s*(1-s),4),"tanh",round(math.tanh(z),4),"dtanh",round(1-math.tanh(z)**2,4),"2sig(2z)-1",round(2*float(sig(2*z))-1,4))
for wv in [1,1.05,1.2]: z=wv*0.9-1; print("w",wv,"z",round(z,3),"step",int(z>0),"sig",round(float(sig(z)),4))
for L in [2,5,10,20]: print("0.25^",L,0.25**L)
a=np.array([0.2,1.3,0.8,2.1]); p=np.exp(a)/np.exp(a).sum(); print("softmax",p.round(4), "prop",(a/a.sum()).round(3),"sig(2.1)",round(float(sig(2.1)),3))
a2=a+10; print("shift",(np.exp(a2)/np.exp(a2).sum()).round(4))
print("softmax(1,3)",(np.exp([1,3])/np.exp([1,3]).sum()).round(4),"sig2",round(float(sig(2)),4))
gelu=lambda x:0.5*x*(1+math.erf(x/math.sqrt(2)))
print("gelu",[round(gelu(x),4) for x in (-1,0,1,2)])
print("== 9.5")
f=lambda x:x**2
for n in [1,2,4,10]:
    t=np.linspace(0,2,n+1); xs=np.linspace(0,2,200001); g=np.interp(xs,t,f(t)); print(n,"maxerr",round(float(np.max(np.abs(g-f(xs)))),5))
xs=np.linspace(0,2,9); print("1relu(x)+2relu(x-1)",relu(xs)+2*relu(xs-1), f(xs))
T=lambda x:2*relu(x)-4*relu(x-0.5)
xs=np.linspace(0,1,9); print("T",T(xs)); print("TT",T(T(xs))); print("TTT x=1/8..",T(T(T(xs))))
def pieces(L,N=2**16):
    xs=np.linspace(0,1,N+1); y=xs.copy()
    for _ in range(L): y=T(y)
    d=np.diff(y); s=np.sign(np.round(d*N,6)); return 1+np.sum(s[1:]!=s[:-1])
print([pieces(L) for L in range(1,6)])
print("abs:",[float(relu(x)+relu(-x)) for x in (-2,-0.5,0,1.5)])
